### ISSUE TITLE
Greyed out Publish dates should be optional

### ISSUE THREAD

**Issue by animaux** [symphonists/unpublishedfilter#6]
They make perfect sense with a future publication date for a blog/news entry. On Dates like future events (meetings and such) they should work the other way round.

Maybe there should be a switch e.g. 

□ no publish filtering on dates
□ dates in the past are greyed out
□ dates in the futre are greyed out

**Comment by nilshoerrmann** [comment]
However you decide to handle this, you should keep in mind that – for the user – the elegance of this extension lies in the simplicity of not having any preferences. Drop it in and it will dim all entries that are either unpublished, hidden or in the future. 

This approach is a bit problematic because it makes a lot of assumptions under the hood. For example, all strings that are used to detect hidden entries need to be hardcorded for all supported languages in order to support systems with different languages per user, see https://github.com/symphonists/unpublishedfilter/commit/325c37a0d7d7db44fa50129e7551426238675385?diff=unified#diff-15f5b0049877597713c49062e0607e66R5.

So a custom preference for one of the given triggers will not solve the real problem of this extension. Instead, it would be a good idea to think about a more advanced but also more generic approach: something like a duplicator in the section setting to map table columns with values ("draft") or conditions ("later than today") that trigger entry dimming.

This would make the extension language independed. It would enable custom trigger strings and conditions as well. Conditions could even be generated automatically from the new 2.6 filter condition panel. And it would still be possible to enable auto-detection by default and use this proposed interface only as advanced setting.

**Comment by nilshoerrmann** [comment]
So maybe this could lead to a more general "dim entries" extension that could also dim entries from the past so it could be used for to do list or such that need to highlight upcomming entries and not past ones.

**Comment by nilshoerrmann** [comment]
If you like a quick fix: This extension adds a special class for dates in the future: `.unpublishedfilter-future`. You could add a custom backend style that resets this class to the normal highlighting without having to edit this extension or add a specific setting to diable this feature.

**Comment by animaux** [comment]
Quick fix for me is to use the current extension and comment out [Line 27](https://github.com/symphonists/unpublishedfilter/blob/master/extension.driver.php#L27) of the `extension.driver.php` … dirty, but it throws no errors and only the checkbox-part is left working.

**Comment by nitriques** [comment]
Great suggestion Nils. I'll see what I can do.
