### ISSUE TITLE
[2.2+] Does not support localizations anymore?

### ISSUE THREAD

**Issue by jurajkapsz** [symphonists/unpublishedfilter#8]
Onwards from the `v2.2` release the extension stopped working for my localization (slovak). I made a quick localization some time ago (times of `v2.1.x`), which worked, but it stopped now after update.

How can we test this. Actually I could commit my localization anyway, don't know why I didn't do it yet. Shall I make a pull request with my localization and we will see from there?

**Comment by jurajkapsz** [comment]
Hah, now I see, the `lang` folder has completely gone from `v2.2`.

Also, I am not a js guru, but the value triggers for unpublished entries are now hardcoded into the js, aren't they?

**Comment by nitriques** [comment]
> Also, I am not a js guru, but the value triggers for unpublished entries are now hardcoded into the js, aren't they?

Yes. I do not know why @nilshoerrmann did that, but he must have a good reason for it. Please feel free to send a PR adding the words needed. (or give me the slovak words and I'll add them).

Thanks.

**Comment by jurajkapsz** [comment]
Ok, I will, thanks for the info.

**Comment by nilshoerrmann** [comment]
> Yes. I do not know why @nilshoerrmann did that, but he must have a good reason for it.

Ha, thanks for believing in me :bowtie:

I understand that the change to remove the `lang` folder and hardcode localisations in the script looks a bit strange at first sight, but there is indeed a good reason for it: **We are searching for strings that are not handled by Symphony's language management.**

This extension searches for strings that represent an entry's status. These strings will never change when the user changes the system language. 

If your system and content language are the same you will never notice any problems but as soon as users have different language preferences in their profiles you'll get into trouble: only those using the same system language as the content language will see unpublished/published highlighting *. For all others the extension will make no difference. Always using all languages to find unpublished entries fixes this issue and this is why the strings are now hardcoded in the script.

---

\* Typical use cases where this happens:

- We develop a site for a client and use the English backend because it's easier for us as developers because the wording across the system, the documentation and Github is the same. Our endusers are German, their content is German and their system language is German. So a filtering based on core localisation won't work for us.
- We develop a site with a multilingual team of editors. System languages will differ across users and you can't guess the content language from the user's language.
- We develop a site with multilingual content which results in different triggers for unpublished entries depending on the entry language (so even the content language might not be distinct).

---

> Also, I am not a js guru, but the value triggers for unpublished entries are now hardcoded into the js, aren't they?

If you'd like to add another language, please add your localisations here for:

- field names representing entry statuses:  
https://github.com/symphonists/unpublishedfilter/blob/master/assets/unpublishedfilter.publish.js#L12
- field names representing entry dates:  
https://github.com/symphonists/unpublishedfilter/blob/master/assets/unpublishedfilter.publish.js#L13
- field values representing the entry status
https://github.com/symphonists/unpublishedfilter/blob/master/assets/unpublishedfilter.publish.js#L16

**Comment by jurajkapsz** [comment]
Thanks for the cool briefing @nilshoerrmann ! I will add a set of slovak words I use to those lines.

One more thing, there is no release or a tag of the latest version - master download does it anyway - but from the [symphonyextensions](http://symphonyextensions.com/extensions/unpublishedfilter/) site you get only 2.2.0 version from the download links; don't know why it happens, if it points to the master.

**Comment by nilshoerrmann** [comment]
> One more thing, there is no release or a tag of the latest version - master download does it anyway - but from the symphonyextensions site you get only 2.2.0 version from the download links; don't know why it happens, if it points to the master. 

I updated the readme and added the missing releases here on Github. That's all I can do: the extension site doesn't know anything about Symphony 2.6.2 which is why it incorrectly displays incompatibilities (there is no specific release for Symphony 2.5 although the extensions states it's compatible).

**Comment by nitriques** [comment]
Thanks Nils!

**Comment by jurajkapsz** [comment]
Speaking of repo cleanup, there is a small typo in repo description: _Greyes out unpu**p**lished entries..._

**Comment by nitriques** [comment]
I wish I could change it, but I do not have the rights. I've asked @brendo to gave them to me :smile:

**Comment by nilshoerrmann** [comment]
I changed it.

**Comment by jurajkapsz** [comment]
Great, I think everything is polished now :) Thanks guys.
